### ISSUE TITLE
osmoBTS-LimeSDR mini 

### ISSUE THREAD

**Issue by jacooooooooool** [egislev/osmoBTS-LimeSDR#1]
hello, can I install ubuntu 18 on RPI4?
LimeSDR mini ??

**Comment by egislev** [comment]
Hello,
i can't confirm that it works, but i try to compile on fresh ubuntu 20 install on RPI 3+ - it works ok.
1. Install LimeSuite. Use "sudo apt install libwxgtk3.0-gtk3-dev" if you want LimeSuiteGUI.
2. "sudo apt install build-essential libtool libortp-dev dahdi-source libsctp-dev shtool autoconf automake git-core pkg-config make gcc cmake libusb-1.0-0-dev libpcsclite-dev libtalloc-dev libortp-dev libsctp-dev libmnl-dev libdbi-dev libdbd-sqlite3 libsqlite3-dev sqlite3 libc-ares-dev libgnutls28-dev libfftw3-dev" Difference is in package libgnutls28-dev name.
3. Run as root "./setup.sh" and follow instructions, packages installation is not required after step 2.
4. RPi 3 has only USB2 port, RPi 4 - has USB3, so it is possible to run.

**Comment by jacooooooooool** [comment]
Thank you very much for help
My system is Ubuntu 18 Server (Rpi4-4gb)
the installation process  ( osmoBTS-LimeSDR) ran smoothly

LimeSDR mini won't cooperate :(  conect to USB3

[https://osmocom.org/issues/3342](url)
One remaining difficulty is to know which port (BAND1/BAND2) is ideal for a given transimt frequency. It seems that the LimeSDR-mini vs. LimeSDR-USB have inverted recommendations about which ports shall be used for which frequency.

reconfiguration of the osmo-trx.cfg tx-path BAND1 to BAND2 file had no effect

can you suggest what the problem is?
Thank you very much
